version: '2'
services:
    loginWebApp:
        container_name: loginWebApp
        image: endimion13/eidas-gr-loginwebapp:2
        expose:
            - 8090
        ports:
            - 8090:8090
        environment:
            - EIDAS_PROPERTIES=CurrentFamilyName,CurrentGivenName,DateOfBirth,PersonIdentifier
            - SP_FAIL_PAGE=https://www.google.com
            - SP_SUCCESS_PAGE=https://www.google.gr
            - SP_BACKEND=http://www.google.gr
            - SP_METADATA_URL=http://138.68.103.237:8090/metadata
            - SP_RETURN_URL=http://138.68.103.237:8090/eidasResponse
            - SP_LOGO=img/app-logo.png
            - SP_CONFIG_REPOSITORY=/confgiEidas
        volumes:
            - /configEidas:/configEidas
            - /keystore:/keystore
